server:
  port: 8081
spring:
  thymeleaf:
    prefix: classpath:/templates/
    suffix: .html
  datasource:
    url: jdbc:mysql://localhost:3306/jizheping?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: root
    druid:
      initial-size: 1 #初始化连接数
      min-idle: 1  #最小空闲连接数
      max-active: 1   #最大活动连接数
      test-on-borrow: true   #获取连接是测试是否可以使用
      stat-view-servlet.allow: true
    mvc:
      static-path-pattern: /**
    redis:
      host: localhost
      port: 6379
      max-wait: 30000  #连接池最大阻塞等待时间(使用负值表示没有限制)
      max-active: 100  #连接池最大连接数(使用负值表示没有限制)
      max-idle: 20     #连接池中的最大空闲连接
      min-idle: 0      #连接池中的最小空闲连接
      timeout: 3000    #连接超时时间
mybatis:
  type-aliases-package: com.jizheping.entity
  mapper-locations: classpath:mapper/*Mapper.xml

